name: gdrive-to-link

on:
  workflow_dispatch:
    inputs:
      DEVICE_IMG:
        description: 'file link'
        required: true
        default: 'https://dumps.tadiphone.dev/dumps/samsung/a05s/-/raw/a05snsdxx-user-14-UP1A.231005.007-A057FXXS5CXH9-release-keys/recovery.img'

jobs:
  build:
    name: Device Tree Generator by ${{ github.actor }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Getting tools ready 
      run: |
        pip install gdown 
    
    - name: Downloading file
      run: |
        mkdir Gdrive && cd Gdrive
        gdown https://drive.google.com/uc?id=${{ github.event.inputs.DEVICE_IMG }}
        
    - name: Set Build Date 
      run: |
        echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
        
    - name: Release
      if: github.event.inputs.RELEASE_FILE == 'true'
      uses: softprops/action-gh-release@v1
      with:
        files: |
          Gdrive/*.*
        name: your file // ${{ env.BUILD_DATE }}
        tag_name: ${{ github.run_id }}
        body: |
